config/routes.rb
Rails.application.routes.draw do
  Blogger::Application.routes.draw do
     
    root to: 'articles#index'

    resources :articles do
      resources :comments
    end
    resources :tags
    resources :authors
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments
  has_many :taggings
  has_many :tags, through: :taggings
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>"}
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
  has_many :attachments

  def tag_list
    tags.join(", ")
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect {|name| Tag.find_or_create_by(name: name)}
    self.tags = new_or_found_tags
  end
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :article
end

app/models/author.rb
class Author < ActiveRecord::Base
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to  :article
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :articles, through: :taggings

  def to_s
    name
  end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :article
  belongs_to :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ArticlesHelper
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params["id"])
    @comment = Comment.new
    @comment.article_id = @article.id
  end

  def new
    @article = Article.new
  end

  def create
    article = Article.new(article_params)
    if article.save
      flash.notice = "#{article.title} created!"
      redirect_to articles_path
    else
      flash.notice = "Try entering a different article"
      render :new
    end
  end

  def destroy
    article = Article.find(params["id"]).destroy
    flash.notice = "#{article.title} deleted!"
    redirect_to articles_path
  end

  def edit
    @article = Article.find(params["id"])
  end

  def update
    article = Article.find(params["id"])
    article.update_attributes(article_params)

    flash.notice = "#{article.title} updated!"
    redirect_to article_path(article)
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include CommentsHelper

  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]

    @comment.save
    redirect_to article_path(@comment.article)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find(params[:id])
  end

  def index
    @tags = Tag.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def article_params
    params.require(:article).permit(:title, :body, :tag_list, :image)
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def comment_params
    params.require(:comment).permit(:author_name, :body)
  end
end

app/views/articles/_comment.html.haml
%div
  %h4 
    Comment by #{comment.author_name} 
  %p 
    Posted #{distance_of_time_in_words(comment.article.created_at, comment.created_at)} ago
  %p.comment= comment.body

app/views/articles/_form.html.haml
= form_for(@article, html: {multipart: true}) do |f|
  = f.label :title
  = f.text_area :title
  %br/
  = f.label :body
  = f.text_area :body
  %br/
  = f.label :tag_list
  = f.text_field :tag_list
  %br/
  - if @article.image.exists?
    = image_tag @article.image.url
  = f.label :image, "Attach an image"
  %br/
  = f.file_field :image
  %br/
  = f.submit 

app/views/articles/edit.html.haml
%h4 Edit an existing article
= render partial: 'form'

app/views/articles/index.html.haml
%h3 All Articles

%ul
  - @articles.each do |article|
    %li= link_to article.title, article_path(article), class: 'article_title'

= link_to 'Create new article', new_article_path, class: 'new_article'

app/views/articles/new.html.haml
%h4 Create a new article
= render partial: 'form'

app/views/articles/show.html.haml
%h4= @article.title
%p
  Tags:
  - @article.tags.each do |tag|
    = link_to tag.name, tag_path(tag)
- if @article.image.exists?
  %p
    = image_tag @article.image.url

= simple_format(@article.body)

= link_to 'Edit article', edit_article_path(@article)
%br/
= link_to 'Remove article', article_path(@article), method: :delete
%br/

%h3 Comments(#{@article.comments.count})
= render partial: 'articles/comment', collection: @article.comments
= render partial: 'comments/form'
= link_to 'Back to articles', articles_path

app/views/authors/_form.html.haml
- form_for(@author) do |f|
  - if @authors.errors.any?
    #error_explanation
      %h2
        = pluralize(@author.errors.count, "error")
        prohibited this author from saved:

      %ul
        - @author.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :username
    %br/
    = f.text_field :username
  .field
    = f.label :email
    %br/
    = f.text_field :email
  .field
    = f.label :password
    %br/
    = f.password_field :password
  .field
    = f.label :password_confirmation
    %br/
    = f.password_field :password_confirmation
  .actions
    = f.submit

app/views/authors/edit.html.haml
<h1>Editing Author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.haml
%p#notice= notice

%h4 Authors

%table
  %thead
    %tr
      %th Username
      %th Email
      %th Password
      %th Password confirmation
      %th{:colspan => "3"}

  %tbody
    - @authors.each do |author|
      %tr
        %td= author.username
        %td= author.email
        %td= author.password
        %td= author.password_confirmation
        %td= link_to 'Show', author
        %td= link_to 'Edit', edit_author_path(author)
        %td= link_to 'Destroy', author, method: :delete, data: {confirm: 'Are you sure?'}
%br/
= link_to 'New Author', new_author_path

app/views/authors/new.html.haml
<h1>New Author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.haml
%p#notice= notice

%p
  %strong Username:
  = @author.username

%p
  %strong Email:
  = @author.email

%p
  %strong Password:
  = @author.password

%p
  %strong Password confirmation:
  = @author.password_confirmation

= link_to 'Edit', edit_author_path(@author)
= link_to 'Back', authors_path

app/views/comments/_form.html.haml
%h3 Post a comment
= form_for([@article, @comment]) do |f|
  = f.label :author_name, 'Your name'
  = f.text_field :author_name
  = f.label :body, 'Your comment'
  = f.text_area :body
  = f.submit 'Post Comment'

app/views/layouts/application.html.haml
!!!
%html
%head
  %title Blogger
  = stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

%body
  %p.flash= flash.notice
  = yield

app/views/tags/index.html.haml
%h5 Tags index

- @tags.each do |tag|
  = simple_format(tag.name)
  %ul
    - tag.articles.each do |article|
      %li= link_to article.title, article_path(article.id)

app/views/tags/show.html.haml
%h1 Articles tagged with #{@tag.name}

%ul
  - @tag.articles.each do |article|
    %li= link_to article.title, article_path(article)
= link_to 'Tags index', tags_path